version: '3.8'

services:
  sharebook-api:
    build:
      context: ../
      dockerfile: Sharebook.API/Dockerfile
    ports:
       - "5292:80"
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"